hotellerie/apps/parloirs/urls.py
""" apps/parloirs/urls.py """

from django.urls import path

from . import views

app_name = 'parloirs'
urlpatterns = [
    path('list/', views.list, name='list'),
    path('create/', views.create, name='create'),
    path('<int:pk>/', views.details, name='details'),
    path('<int:pk>/update/', views.update, name='update'),
    path('<int:pk>/delete/', views.delete, name='delete'),
]

hotellerie/apps/parloirs/models.py
""" apps/parloirs/models.py """

from django.db import models

from apps.personnes.models import Personne


class Parloir(models.Model):
    """ Parloir model. """
    personne_1 = models.ForeignKey(
        to=Personne,
        on_delete=models.CASCADE,
        related_name='parloir_personne_1',
    )
    personne_2 = models.ForeignKey(
        null=True,
        to=Personne,
        on_delete=models.CASCADE,
        related_name='parloir_personne_2',
    )
    personne_3 = models.ForeignKey(
        null=True,
        to=Personne,
        on_delete=models.CASCADE,
        related_name='parloir_personne_3',
    )
    date = models.DateField()
    REPAS_NAMES = [
        ('Non défini', '---------'),
        ('Petit déjeuner', 'Petit déjeuner'),
        ('Déjeuner', 'Déjeuner'),
        ('Dîner', 'Dîner'),
    ]
    repas = models.CharField(
        max_length=50,
        choices=REPAS_NAMES,
    )
    nombre = models.IntegerField()
    PARLOIRS_NAMES = [
        ('Non défini', '---------'),
        ('Saint-Benoît', 'Saint-Benoît'),
        ('Saint-Ignace', 'Saint-Ignace'),
        ('Saint-Dominique', 'Saint-Dominique'),
        ('Parloir 1 vélux', 'Parloir 1 vélux'),
        ('Parloir 2 vélux', 'Parloir 2 vélux'),
        ('Salle de projection', 'Projection'),
    ]
    parloir = models.CharField(
        max_length=50,
        choices=PARLOIRS_NAMES,
    )
    repas_apporte = models.BooleanField(
        default=False,
    )
    remarque = models.TextField()
    created_at = models.DateTimeField(
        auto_now_add=True,
    )
    last_modified = models.DateTimeField(
        auto_now=True,
    )

    def moines_string(self):
        """ Returns the monks concerned by the parloir as a string. """
        moines = self.personne_1.__str__()
        moines += ' + ' + self.personne_2.__str__() if self.personne_2 else ''
        moines += ' + ' + self.personne_3.__str__() if self.personne_3 else ''
        return moines

    def __str__(self):
        return "{} le {}".format(
            self.moines_string(),
            self.date.strftime('%d/%m/%Y'),
        )

hotellerie/apps/parloirs/forms.py
""" apps/parloirs/forms.py """

from dal import autocomplete

from django import forms
from tempus_dominus.widgets import DatePicker

from apps.personnes.models import Personne
from .models import Parloir


class ParloirForm(forms.ModelForm):
    """ Form for Parloirs. """
    personne_1 = forms.ModelChoiceField(
        label='Moine 1 :',
        error_messages={
            'required': 'Ce champ est obligatoire',
        },
        queryset=Personne.objects.all(),
        widget=autocomplete.ModelSelect2(url='personnes:autocomplete_monks'),
    )
    personne_2 = forms.ModelChoiceField(
        label='Moine 2 :',
        required=False,
        queryset=Personne.objects.all(),
        widget=autocomplete.ModelSelect2(url='personnes:autocomplete_monks'),
    )
    personne_3 = forms.ModelChoiceField(
        label='Moine 3 :',
        required=False,
        queryset=Personne.objects.all(),
        widget=autocomplete.ModelSelect2(url='personnes:autocomplete_monks'),
    )
    date = forms.DateField(
        label='Date :',
        input_formats=[
            '%d/%m/%Y',
        ],
        widget=DatePicker(options={
            'format': 'DD/MM/YYYY',
        }),
    )
    repas = forms.ChoiceField(
        choices=[
            ('Non défini', '---------'),
            ('Petit déjeuner', 'Petit déjeuner'),
            ('Déjeuner', 'Déjeuner'),
            ('Dîner', 'Dîner'),
        ],
    )
    nombre = forms.IntegerField(
        help_text="Nombre de personnes en plus des personnes ci-dessus",
        widget=forms.NumberInput(
            attrs={
                'placeholder': 0,
            }
        )
    )
    parloir = forms.ChoiceField(
        label="Parloir :",
        choices=[
            ('Non défini', '---------'),
            ('Saint-Benoît', 'Saint-Benoît'),
            ('Saint-Ignace', 'Saint-Ignace'),
            ('Saint-Dominique', 'Saint-Dominique'),
            ('Parloir 1 vélux', 'Parloir 1 vélux'),
            ('Parloir 2 vélux', 'Parloir 2 vélux'),
            ('Salle de projection', 'Projection'),
        ],
    )
    repas_apporte = forms.BooleanField(
        required=False,
        label='Repas apporté',
        label_suffix='',
    )
    remarque = forms.CharField(
        required=False,
        label='Remarques :',
        widget=forms.Textarea,
    )

    class Meta:
        model = Parloir
        fields = ('__all__')

hotellerie/apps/parloirs/views.py
""" apps/parloirs/views.py """


from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render, reverse
from django.contrib.auth.decorators import login_required

from .forms import ParloirForm
from .models import Parloir


@login_required
def list(request):
    """ List of Parloirs. """
    parloirs = Parloir.objects.all().order_by('-date')
    return render(request, 'parloirs/list.html', {'parloirs': parloirs})


@login_required
def create(request):
    """ Create a Parloir. """
    if request.method == 'POST':
        form = ParloirForm(request.POST)

        if form.is_valid():
            form.save()
            date = form.cleaned_data['date']
            return HttpResponseRedirect(reverse('main:calendar', kwargs={
                'day': '{:%d}'.format(date),
                'month': '{:%m}'.format(date),
                'year': '{:%Y}'.format(date),
            }))

    form = ParloirForm()

    return render(request, 'parloirs/form.html', {'form': form})


@login_required
def details(request, *args, **kwargs):
    """ Details of a Parloir. """
    parloir = get_object_or_404(Parloir, id=kwargs['pk'])

    return render(request, 'parloirs/details.html', {
        'parloir': parloir,
        'calendar_day': parloir.date.strftime('%d'),
        'calendar_month': parloir.date.strftime('%m'),
        'calendar_year': parloir.date.strftime('%Y')
    })


@login_required
def update(request, *args, **kwargs):
    """ Update a Parloir. """
    parloir = get_object_or_404(Parloir, pk=kwargs['pk'])

    if request.method == 'POST':
        form = ParloirForm(request.POST, instance=parloir)
        if form.is_valid():
            form.save()
            date = form.cleaned_data['date']
            return HttpResponseRedirect(reverse('main:calendar', kwargs={
                'day': '{:%d}'.format(date),
                'month': '{:%m}'.format(date),
                'year': '{:%Y}'.format(date),
            }))

    form = ParloirForm(instance=parloir)

    return render(request, 'parloirs/form.html', {
        'form': form,
        'parloir': parloir,
    })


@login_required
def delete(request, *args, **kwargs):
    """ Delete a Parloir. """
    parloir = get_object_or_404(Parloir, pk=kwargs['pk'])

    if request.method == 'POST':
        form = ParloirForm(request.POST, instance=parloir)
        parloir.delete()
        return HttpResponseRedirect(reverse('main:calendar'))

    form = ParloirForm(instance=parloir)

    return render(request, 'parloirs/delete.html', {
        'form': form,
        'parloir': parloir,
    })

hotellerie/apps/parloirs/templates/parloirs/delete.html
{% extends 'main.html' %}

{% load static %}

{% block breadcrumbs %}
    <li class="breadcrumb-item"><a href={% url 'parloirs:list' %}>Parloirs</a></li>
    <li class="breadcrumb-item"><a href={% url 'parloirs:details' parloir.id %}>{{ parloir }}</a></li>
    <li class="breadcrumb-item active">Supprimer</li>
{% endblock breadcrumbs %}

{% block content %}
    <form method="post">
        {% csrf_token %}

        <h6>Êtes-vous sûr de vouloir supprimer ce parloir ?</h6>

        <!-- Validation -->
        <div class="d-flex justify-content-center">
            <button type="submit" class="btn btn-success mx-3">Oui</button>
            <a href={% url 'parloirs:details' parloir.id %} class="btn btn-primary mx-3">Non</a>
        </div>
    </form>
{% endblock %}

hotellerie/apps/parloirs/templates/parloirs/details.html
{% extends 'main.html' %}

{% load static %}

{% block breadcrumbs %}
    <li class="breadcrumb-item"><a href={% url 'parloirs:list' %}>Parloirs</a></li>
    <li class="breadcrumb-item active">{{ parloir }}</li>
{% endblock breadcrumbs %}

{% block content %}
    <h2>Parloir de {{ parloir.moines_string }}</h2>

    <div class="row">
        <a href={% url 'parloirs:update' parloir.id %} class="mx-1">Modifier</a>
        <a href={% url 'parloirs:delete' parloir.id %} class="mx-1">Supprimer</a>
        <a href={% url 'main:calendar' %} class="mx-1">Retour au calendrier</a>
    </div>

    <div class="col-6">
        <table class="table table-sm">
            <tr>
                <td>Nombre en plus de la personne :</td>
                <td>{{ parloir.nombre }}</td>
            </tr>

            <tr>
                <td>Date :</td>
                <td>{{ parloir.date }} ({{ parloir.repas }})</td>
            </tr>

            <tr>
                <td>Parloir :</td>
                <td>{{ parloir.parloir }}</td>
            </tr>

            <tr>
                <td>Repas apporté :</td>
                <td>{{ parloir.repas_apporte|yesno:'Oui,Non' }}</td>
            </tr>
            
            <tr>
                <td>Remarques :</td>
                <td>{{ parloir.remarque }}</td>
            </tr>
        </table>
    </div>
{% endblock %}

hotellerie/apps/parloirs/templates/parloirs/form.html
{% extends 'main.html' %}

{% load static %}
{% load widget_tweaks %}

{% block breadcrumbs %}
    <li class="breadcrumb-item"><a href={% url 'parloirs:list' %}>Parloirs</a></li>

    {% if parloir %}
        <li class="breadcrumb-item"><a href={% url 'parloirs:details' parloir.id %}>{{ parloir }}</a></li>
        <li class="breadcrumb-item active">Modifier</li>
    {% else %}
        <li class="breadcrumb-item active">Créer</li>
    {% endif %}
{% endblock breadcrumbs %}

{% block content %}
    {% if parloir %}
        <h2>{{ parloir }}</h2>
    {% else %}
        <h2>Créer un nouveau parloir</h2>
    {% endif %}

    <form method="post" novalidate>
        {% csrf_token %}

        <!-- Moine 1 -->
        <div class="form-group">
            {{ form.personne_1.label_tag }}

            {% if form.is_bound %}
                {% if form.personne_1.errors %}
                    {% render_field form.personne_1 class="form-control is-invalid" %}
                    {% for error in form.personne_1.errors %}
                        <div class="invalid-feedback" style="display: block;">
                            {{ error }}
                        </div>
                    {% endfor %}
                {% else %}
                    {% render_field form.personne_1 class="form-control is-valid" %}
                {% endif %}
            {% else %}
                {% render_field form.personne_1 class="form-control" %}
            {% endif %}

            {% if form.personne_1.help_text %}
                <small class="form-text text-muted">
                    {{ form.personne_1.help_text }}
                </small>
            {% endif %}

            {% if sejour %}
                <small class="form-text text-muted"><a href={% url 'personnes:details' sejour.personne.id %}>Voir la fiche de cette personne</a></small>
            {% endif %}
        </div>


        <!-- Moine 2 -->
        <div class="form-group">
            {{ form.personne_2.label_tag }}

            {% if form.is_bound %}
                {% if form.personne_2.errors %}
                    {% render_field form.personne_2 class="form-control is-invalid" %}
                    {% for error in form.personne_2.errors %}
                        <div class="invalid-feedback" style="display: block;">
                            {{ error }}
                        </div>
                    {% endfor %}
                {% else %}
                    {% render_field form.personne_2 class="form-control is-valid" %}
                {% endif %}
            {% else %}
                {% render_field form.personne_2 class="form-control" %}
            {% endif %}

            {% if form.personne_2.help_text %}
                <small class="form-text text-muted">
                    {{ form.personne_2.help_text }}
                </small>
            {% endif %}

            {% if sejour %}
                <small class="form-text text-muted"><a href={% url 'personnes:details' sejour.personne.id %}>Voir la fiche de cette personne</a></small>
            {% endif %}
        </div>


        <!-- Moine 3 -->
        <div class="form-group">
            {{ form.personne_3.label_tag }}

            {% if form.is_bound %}
                {% if form.personne_3.errors %}
                    {% render_field form.personne_3 class="form-control is-invalid" %}
                    {% for error in form.personne_3.errors %}
                        <div class="invalid-feedback" style="display: block;">
                            {{ error }}
                        </div>
                    {% endfor %}
                {% else %}
                    {% render_field form.personne_3 class="form-control is-valid" %}
                {% endif %}
            {% else %}
                {% render_field form.personne_3 class="form-control" %}
            {% endif %}

            {% if form.personne_3.help_text %}
                <small class="form-text text-muted">
                    {{ form.personne_3.help_text }}
                </small>
            {% endif %}

            {% if sejour %}
                <small class="form-text text-muted"><a href={% url 'personnes:details' sejour.personne.id %}>Voir la fiche de cette personne</a></small>
            {% endif %}
        </div>


        <!-- Nombre -->
        <div class="row justify-content-start ml-0">
            {{ form.nombre.label_tag }}

            <div class="form-group">
                {% if form.is_bound %}
                    {% if form.nombre.errors %}
                        {% render_field form.nombre class="form-control is-invalid" %}
                        {% for error in form.nombre.errors %}
                            <div class="invalid-feedback" style="display: block;">
                                {{ error }}
                            </div>
                        {% endfor %}
                    {% else %}
                        {% render_field form.nombre class="form-control is-valid" %}
                    {% endif %}
                {% else %}
                    {% render_field form.nombre class="form-control" %}
                {% endif %}
                
                {% if form.nombre.help_text %}
                    <small class="form-text text-muted">
                        {{ form.nombre.help_text }}
                    </small>
                {% endif %}
            </div>
        </div>


        <!-- Date -->
        <div class="row justify-content-start ml-0">
            {{ form.date.label_tag }}

            <div class="form-group">
                {% if form.is_bound %}
                    {% if form.date.errors %}
                        {% render_field form.date class="form-control is-invalid" %}
                        {% for error in form.date.errors %}
                            <div class="invalid-feedback" style="display: block;">
                                {{ error }}
                            </div>
                        {% endfor %}
                    {% else %}
                        {% render_field form.date class="form-control is-valid" %}
                    {% endif %}
                {% else %}
                    {% render_field form.date class="form-control" %}
                {% endif %}

                {% if form.date.help_text %}
                    <small class="form-text text-muted">
                        {{ form.date.help_text }}
                    </small>
                {% endif %}
            </div>
        </div>


        <!-- Repas -->
        <div class="row justify-content-start ml-0">
            {{ form.repas.label_tag }}

            <div class="form-group">
                {% if form.is_bound %}
                    {% if form.repas.errors %}
                        {% render_field form.repas class="form-control is-invalid" %}
                        {% for error in form.repas.errors %}
                            <div class="invalid-feedback" style="display: block;">
                                {{ error }}
                            </div>
                        {% endfor %}
                    {% else %}
                        {% render_field form.repas class="form-control is-valid" %}
                    {% endif %}
                {% else %}
                    {% render_field form.repas class="form-control" %}
                {% endif %}

                {% if form.repas.help_text %}
                    <small class="form-text text-muted">
                        {{ form.repas.help_text }}
                    </small>
                {% endif %}
            </div>
        </div>


        <!-- Parloir -->
        <div class="row justify-content-start ml-0">
            {{ form.parloir.label_tag }}

            <div class="form-group">
                {% if form.is_bound %}
                    {% if form.parloir.errors %}
                        {% render_field form.parloir class="form-control is-invalid" %}
                        {% for error in form.parloir.errors %}
                            <div class="invalid-feedback" style="display: block;">
                                {{ error }}
                            </div>
                        {% endfor %}
                    {% else %}
                        {% render_field form.parloir class="form-control is-valid" %}
                    {% endif %}
                {% else %}
                    {% render_field form.parloir class="form-control" %}
                {% endif %}

                {% if form.parloir.help_text %}
                    <small class="form-text text-muted">
                        {{ form.parloir.help_text }}
                    </small>
                {% endif %}
            </div>
        </div>


        <!-- Repas apporté -->
        <div class="d-flex my-2">
            {% if form.is_bound %}
                {% if form.repas_apporte.errors %}
                    {% render_field form.repas_apporte class="form-control is-invalid" %}
                    {% for error in form.repas_apporte.errors %}
                        <div class="invalid-feedback" style="display: block;">
                            {{ error }}
                        </div>
                    {% endfor %}
                {% else %}
                    {% render_field form.repas_apporte class="form-control is-valid" %}
                {% endif %}
            {% else %}
                {% render_field form.repas_apporte class="form-control" %}
            {% endif %}

            {% if form.repas_apporte.help_text %}
                <small class="form-text text-muted">
                    {{ form.repas_apporte.help_text }}
                </small>
            {% endif %}

            {{ form.repas_apporte.label_tag }}
        </div>

        <!-- Commentaire -->
        <div class="form-group">
            {{ form.remarque.label_tag }}
            {% if form.is_bound %}
                {% if form.remarque.errors %}
                    {% render_field form.remarque class="form-control is-invalid" %}
                    {% for error in form.remarque.errors %}
                        <div class="invalid-feedback" style="display: block;">
                            {{ error }}
                        </div>
                    {% endfor %}
                {% else %}
                    {% render_field form.remarque class="form-control is-valid" %}
                {% endif %}
            {% else %}
                {% render_field form.remarque class="form-control" %}
            {% endif %}
            
            {% if form.remarque.help_text %}
                <small class="form-text text-muted">
                    {{ form.remarque.help_text }}
                </small>
            {% endif %}
        </div>


        <!-- Validation -->
        <div class="d-flex justify-content-center">
            {% if parloir %}
                <a href={% url 'parloirs:details' parloir.id %} class="btn btn-primary mx-3">Annuler</a>
            {% else %}
                <a href={% url 'parloirs:list' %} class="btn btn-primary mx-3">Annuler</a>
            {% endif %}
            <button type="submit" class="btn btn-success mx-3">Valider</button>
        </div>
    </form>
{% endblock %}

{% block javascript %}
    {{ form.media }}
{% endblock javascript %}

hotellerie/apps/parloirs/templates/parloirs/list.html
{% extends 'main.html' %}

{% block breadcrumbs %}
    <li class="breadcrumb-item active">Parloirs</li>
{% endblock breadcrumbs %}

{% block content %}
    <h1 class="mb-3">Parloirs</h1>

    <div class="col-6">
        <div class="text-center mb-4">
            <a href={% url 'parloirs:create' %}>Ajouter un parloir</a>
        </div>

        <table class="table table-sm table-bordered">
            {% for parloir in parloirs %}
                <tr>
                    <td>{{ parloir.moines_string }} ({{ parloir.date }})</td>
                    <td class="text-center">
                        <a href={% url 'parloirs:details' parloir.id %}>
                            <span class="fas fa-eye" title="Voir les détails"></span>
                        </a>
                    </td>
                </tr>
            {% endfor %}
        </table>
    </div>
{% endblock content %}