hotellerie/apps/sejours/urls.py
""" apps/sejours/urls.py """

from django.urls import path

from . import views

app_name = 'sejours'
urlpatterns = [
    path('list/', views.list, name='list'),
    path('create/', views.create, name='create'),
    path('<int:pk>/', views.details, name='details'),
    path('<int:pk>/update/', views.update, name='update'),
    path('<int:pk>/delete/', views.delete, name='delete'),
    path('rooms/', views.get_rooms_status, name='rooms'),
]

hotellerie/apps/sejours/templates/sejours/delete.html
{% extends 'main.html' %}

{% load static %}

{% block breadcrumbs %}
    <li class="breadcrumb-item"><a href={% url 'sejours:list' %}>Séjours</a></li>
    <li class="breadcrumb-item"><a href={% url 'sejours:details' sejour.id %}>{{ sejour }}</a></li>
    <li class="breadcrumb-item active">Supprimer</li>
{% endblock breadcrumbs %}

{% block content %}
    <form method="post">
        {% csrf_token %}

        <h6>Êtes-vous sûr de vouloir supprimer ce séjour ?</h6>

        <!-- Validation -->
        <div class="d-flex justify-content-center">
            <button type="submit" class="btn btn-success mx-3">Oui</button>
            <a href={% url 'sejours:details' sejour.id %} class="btn btn-primary mx-3">Non</a>
        </div>
    </form>
{% endblock %}

hotellerie/apps/sejours/templates/sejours/details.html
{% extends 'main.html' %}

{% load static %}

{% block breadcrumbs %}
    <li class="breadcrumb-item"><a href={% url 'sejours:list' %}>Séjours</a></li>
    <li class="breadcrumb-item active">{{ sejour }}</li>
{% endblock breadcrumbs %}

{% block content %}
    <h2>Séjour de {{ sejour.personne }}</h2>

    <div class="row">
        <a href={% url 'sejours:update' sejour.id %} class="mx-1">Modifier</a>
        <a href={% url 'sejours:delete' sejour.id %} class="mx-1">Supprimer</a>
        <a href={% url 'main:calendar' %} class="mx-1">Retour au calendrier</a>
    </div>

    <div class="col-6">
        <table class="table table-sm">
            <tr>
                <td>Du</td>
                <td>{{ sejour.sejour_du }} {{ sejour.repas_du }}</td>
            </tr>

            <tr>
                <td>Au</td>
                <td>{{ sejour.sejour_au }} {{ sejour.repas_au }}</td>
            </tr>

            <tr>
                <td>Chambres :</td>
                <td>{{ chambres }}</td>
            </tr>

            <tr>
                <td>Table :</td>
                <td>{{ sejour.mensa }}</td>
            </tr>

            <tr>
                <td>Prêtre avec Messe :</td>
                <td>{{ sejour.pretre|yesno:'Oui,Non' }}</td>
            </tr>

            {% comment %} <tr>
                <td>Messe lendemain :</td>
                <td>{{ sejour.messe_lendemain|yesno:'Oui,Non' }}</td>
            </tr> {% endcomment %}

            <tr>
                <td>Messe le premier jour :</td>
                <td>{{ sejour.messe_premier_jour|yesno:'Oui,Non' }}</td>
            </tr>

            <tr>
                <td>Tour de Messe :</td>
                <td>{{ sejour.tour_messe }}</td>
            </tr>

            <tr>
                <td>Servant :</td>
                <td>{{ sejour.servant|yesno:'Oui,Non' }}</td>
            </tr>

            <tr>
                <td>Oratoire :</td>
                <td>{{ sejour.oratoire|default:'Non défini' }}</td>
            </tr>

            <tr>
                <td>Commentaire cuisine :</td>
                <td>{{ sejour.commentaire_cuisine|default_if_none:'' }}</td>
            </tr>

            <tr>
                <td>Commentaire sacristie :</td>
                <td>{{ sejour.commentaire_sacristie|default_if_none:'' }}</td>
            </tr>

            <tr>
                <td>Commentaire listing :</td>
                <td>{{ sejour.commentaire_listing|default_if_none:'' }}</td>
            </tr>
        </table>
    </div>
{% endblock %}

hotellerie/apps/sejours/templates/sejours/home.html
{% extends 'main.html' %}

{% block content %}
    <h1>Bienvenue sur le site de l'hôtellerie !</h1>
{% endblock content %}

hotellerie/apps/sejours/templates/sejours/list.html
{% extends 'main.html' %}

{% block breadcrumbs %}
    <li class="breadcrumb-item active">Séjours</li>
{% endblock breadcrumbs %}

{% block content %}
    <h1 class="mb-3">Séjours</h1>

    <div class="col-9">
        <div class="text-center mb-4">
            <a href={% url 'sejours:create' %}>Ajouter un séjour</a>
        </div>

        <table class="table table-sm table-bordered">
            {% for sejour in sejours %}
                <tr>
                    <td>{{ sejour }}</td>
                    <td class="text-center">
                        <a href={% url 'sejours:details' sejour.id %}>
                            <span class="fas fa-eye" title="Voir les détails"></span>
                        </a>
                    </td>
                </tr>
            {% endfor %}
        </table>
    </div>
{% endblock content %}