hotellerie/apps/retreats/urls.py
""" apps/retreats/urls.py """

from django.urls import path

from . import views

app_name = 'retreats'
urlpatterns = [
    path('list/', views.list, name='list'),
    path('create/', views.create, name='create'),
    path('<int:pk>/', views.details, name='details'),
    path('<int:pk>/update/', views.update, name='update'),
    path('<int:pk>/delete/', views.delete, name='delete'),
]

hotellerie/apps/retreats/models.py
""" apps/retreats/.models.py """

import datetime

from django.db import models


class Retreat(models.Model):
    """ Retreat model. """
    date_from = models.DateField()
    duration = models.IntegerField()

    def date_to(self):
        """ Returns the date_to of a retreat. """
        return self.date_from + datetime.timedelta(days=self.duration)

    def date_to_string(self):
        """ Returns the date_to as a string of a retreat. """
        return self.date_to().strftime('%d/%m/%Y')

    def __str__(self):
        return 'Retraite du {} au {}'.format(
            self.date_from.strftime('%d/%m/%Y'),
            self.date_to_string()
        )

hotellerie/apps/retreats/forms.py
""" apps/personnes/forms.py """

from django import forms

from tempus_dominus.widgets import DatePicker

from .models import Retreat


class RetreatForm(forms.ModelForm):
    """ Form for Personnes. """
    date_from = forms.DateField(
        label='Date :',
        input_formats=[
            '%d/%m/%Y',
        ],
        widget=DatePicker(options={
            'format': 'DD/MM/YYYY',
        }),
    )
    duration = forms.IntegerField(
        label='Durée :',
        label_suffix='',
        initial=5,
    )

    class Meta:
        model = Retreat
        fields = ['date_from', 'duration']

hotellerie/apps/retreats/views.py
""" apps/retreats/views.py """


from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse


from .forms import RetreatForm
from .models import Retreat


@login_required
def list(request):
    """ List of retreats. """
    retreats = Retreat.objects.all().order_by('-date_from')
    return render(
        request,
        'retreats/list.html',
        {
            'retreats': retreats,
        }
    )


@login_required
def create(request):
    """ Create a Retreat. """
    if request.method == 'POST':
        form = RetreatForm(request.POST)

        if form.is_valid():
            form.save()
            date = form.cleaned_data['date_from']
            return HttpResponseRedirect(reverse('main:calendar', kwargs={
                'day': '{:%d}'.format(date),
                'month': '{:%m}'.format(date),
                'year': '{:%Y}'.format(date),
            }))

    form = RetreatForm()

    return render(request, 'retreats/form.html', {'form': form})


@login_required
def details(request, *args, **kwargs):
    """ Details of a Retreat. """
    retreat = get_object_or_404(Retreat, pk=kwargs['pk'])
    return render(request, 'retreats/details.html', {
        'retreat': retreat
    })


@login_required
def update(request, **kwargs):
    """ Update a Retreat. """
    retreat = get_object_or_404(Retreat, pk=kwargs['pk'])

    if request.method == 'POST':
        form = RetreatForm(request.POST, instance=retreat)

        if form.is_valid():
            form.save()
            date = form.cleaned_data['date_from']
            return HttpResponseRedirect(reverse('main:calendar', kwargs={
                'day': '{:%d}'.format(date),
                'month': '{:%m}'.format(date),
                'year': '{:%Y}'.format(date),
            }))

    form = RetreatForm(instance=retreat)

    return render(request, 'retreats/form.html', {
        'form': form,
        'retreat': retreat,
    })


@login_required
def delete(request, **kwargs):
    """ Delete a Retreat. """
    retreat = get_object_or_404(Retreat, pk=kwargs['pk'])

    if request.method == 'POST':
        form = RetreatForm(request.POST, instance=retreat)
        retreat.delete()
        return HttpResponseRedirect(reverse('main:calendar'))

    form = RetreatForm(instance=retreat)

    return render(request, 'retreats/delete.html', {
        'form': form,
        'retreat': retreat,
    })

hotellerie/apps/retreats/templates/retreats/delete.html
{% extends 'main.html' %}

{% load static %}

{% block breadcrumbs %}
    <li class="breadcrumb-item"><a href={% url 'retreats:list' %}>Retraites</a></li>
    <li class="breadcrumb-item"><a href={% url 'retreats:details' retreat.id %}>{{ retreat }}</a></li>
    <li class="breadcrumb-item active">Supprimer</li>
{% endblock breadcrumbs %}

{% block content %}
    <form method="post">
        {% csrf_token %}

        <h6>Êtes-vous sûr de vouloir supprimer cette retraite ?</h6>

        <!-- Validation -->
        <div class="d-flex justify-content-center">
            <button type="submit" class="btn btn-success mx-3">Oui</button>
            <a href={% url 'retreats:details' retreat.id %} class="btn btn-primary mx-3">Non</a>
        </div>
    </form>
{% endblock %}

hotellerie/apps/retreats/templates/retreats/details.html
{% extends 'main.html' %}

{% load static %}

{% block breadcrumbs %}
    <li class="breadcrumb-item"><a href={% url 'retreats:list' %}>Retraites</a></li>
    <li class="breadcrumb-item active">{{ retreat }}</li>
{% endblock breadcrumbs %}

{% block content %}
    <h2 class="mb-3">
        Du {{ retreat.date_from }} au {{ retreat.date_to }}
    </h2>

    <div class="row">
        <a href={% url 'retreats:update' retreat.id %} class="mx-1">Modifier</a>
        <a href={% url 'retreats:delete' retreat.id %} class="mx-1">Supprimer</a>
        <a href={% url 'main:calendar' %} class="mx-1">Retour au calendrier</a>
    </div>
{% endblock %}

hotellerie/apps/retreats/templates/retreats/form.html
{% extends 'main.html' %}

{% load static %}
{% load widget_tweaks %}

{% block breadcrumbs %}
    <li class="breadcrumb-item"><a href={% url 'retreats:list' %}>Retraites</a></li>

    {% if retreat %}
        <li class="breadcrumb-item"><a href={% url 'retreats:details' retreat.id %}>{{ retreat }}</a></li>
        <li class="breadcrumb-item active">Modifier</li>
    {% else %}
        <li class="breadcrumb-item active">Créer</li>
    {% endif %}
{% endblock breadcrumbs %}

{% block content %}
    {% if retreat %}
        <h2 class="mb-4">Modifier une retraite</h2>
    {% else %}
        <h2 class="mb-4">Créer une nouvelle retraite</h2>
    {% endif %}

    <form class="col-3" method="post" novalidate>
        {% csrf_token %}

        <!-- Date from -->
        <div class="row justify-content-between ml-0">
            {{ form.date_from.label_tag }}

            <div class="form-group">
                {% if form.is_bound %}
                    {% if form.date_from.errors %}
                        {% render_field form.date_from class="form-control is-invalid" %}
                        {% for error in form.date_from.errors %}
                            <div class="invalid-feedback" style="display: block;">
                                {{ error }}
                            </div>
                        {% endfor %}
                    {% else %}
                        {% render_field form.date_from class="form-control is-valid" %}
                    {% endif %}
                {% else %}
                    {% render_field form.date_from class="form-control" %}
                {% endif %}

                {% if form.date_from.help_text %}
                    <small class="form-text text-muted">
                        {{ form.date_from.help_text }}
                    </small>
                {% endif %}
            </div>
        </div>

        <!-- Duration -->
        <div class="row justify-content-between ml-0">
            {{ form.duration.label_tag }}

            <div class="form-group">
                {% if form.is_bound %}
                    {% if form.duration.errors %}
                        {% render_field form.duration class="form-control is-invalid" %}
                        {% for error in form.duration.errors %}
                            <div class="invalid-feedback" style="display: block;">
                                {{ error }}
                            </div>
                        {% endfor %}
                    {% else %}
                        {% render_field form.duration class="form-control is-valid" %}
                    {% endif %}
                {% else %}
                    {% render_field form.duration class="form-control" %}
                {% endif %}

                {% if form.duration.help_text %}
                    <small class="form-text text-muted">
                        {{ form.duration.help_text }}
                    </small>
                {% endif %}
            </div>
        </div>

        <!-- Validation -->
        <div class="d-flex justify-content-center mt-5">
            {% if retreat %}
                <a href={% url 'retreats:details' retreat.id %} class="btn btn-primary mx-3">Annuler</a>
            {% else %}
                <a href={% url 'retreats:list' %} class="btn btn-primary mx-3">Annuler</a>
            {% endif %}
            <button type="submit" class="btn btn-success mx-3">Valider</button>
        </div>
    </form>
{% endblock %}

{% block javascript %}
    {{ form.media }}
{% endblock javascript %}

hotellerie/apps/retreats/templates/retreats/list.html
{% extends 'main.html' %}

{% block breadcrumbs %}
    <li class="breadcrumb-item active">Retraites</li>
{% endblock breadcrumbs %}

{% block content %}
    <h1 class="mb-3">Retraites</h1>

    <div class="col-6">
        <div class="text-center mb-4">
            <a href={% url 'retreats:create' %}>Ajouter une retraite</a>
        </div>

        <table class="table table-sm table-bordered">
            {% for retreat in retreats %}
                <tr>
                    <td>Retraite du {{ retreat.date_from }} au {{ retreat.date_to }}</td>
                    <td class="text-center">
                        <a href={% url 'retreats:details' retreat.id %}>
                            <span class="fas fa-eye" title="Voir les détails"></span>
                        </a>
                    </td>
                </tr>
            {% endfor %}
        </table>
    </div>
{% endblock content %}