hotellerie/apps/accounts/urls.py
""" apps/accounts/urls.py """

from django.contrib.auth.views import LogoutView
from django.urls import path

from . import views

app_name = 'accounts'
urlpatterns = [
    path('login', views.HotellerieLoginView.as_view(), name='login'),
    path('logout', LogoutView.as_view(), name='logout'),
]

hotellerie/apps/listings/urls.py
""" apps/listings/urls.py """

from django.urls import path

from . import views

app_name = 'listings'
urlpatterns = [
    path('cuisine/', views.cuisine, name='cuisine'),
    path('hotellerie/', views.hotellerie, name='hotellerie'),
]

hotellerie/apps/main/urls.py
""" apps/main/urls.py """

from django.urls import path, re_path

from . import views

app_name = 'main'
urlpatterns = [
    path('', views.calendar, name='calendar'),
    path('calendar/', views.calendar, name='calendar'),
    re_path(r'^calendar/(?P<day>\d{2})/(?P<month>\d{2})/(?P<year>\d{4})/$',
            views.calendar, name='calendar'),
]

hotellerie/apps/parloirs/urls.py
""" apps/parloirs/urls.py """

from django.urls import path

from . import views

app_name = 'parloirs'
urlpatterns = [
    path('list/', views.list, name='list'),
    path('create/', views.create, name='create'),
    path('<int:pk>/', views.details, name='details'),
    path('<int:pk>/update/', views.update, name='update'),
    path('<int:pk>/delete/', views.delete, name='delete'),
]

hotellerie/apps/sejours/urls.py
""" apps/sejours/urls.py """

from django.urls import path

from . import views

app_name = 'sejours'
urlpatterns = [
    path('list/', views.list, name='list'),
    path('create/', views.create, name='create'),
    path('<int:pk>/', views.details, name='details'),
    path('<int:pk>/update/', views.update, name='update'),
    path('<int:pk>/delete/', views.delete, name='delete'),
    path('rooms/', views.get_rooms_status, name='rooms'),
]

hotellerie/hotellerie/urls.py
""" hotellerie/urls.py """

from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('hotellerie/', include('apps.main.urls')),
    path('hotellerie/accounts/', include('apps.accounts.urls')),
    path('hotellerie/personnes/', include('apps.personnes.urls')),
    path('hotellerie/sejours/', include('apps.sejours.urls')),
    path('hotellerie/parloirs/', include('apps.parloirs.urls')),
    path('hotellerie/retreats/', include('apps.retreats.urls')),
    path('hotellerie/listings/', include('apps.listings.urls')),
    path('hotellerie/admin/', admin.site.urls),
]

hotellerie/apps/main/views.py
""" apps/main.views.py """

import datetime

from django.contrib.auth.decorators import login_required
from django.shortcuts import redirect, render
from django.urls import reverse

from apps.parloirs.models import Parloir
from apps.retreats.models import Retreat
from apps.sejours.models import Sejour


@login_required
def calendar(request, *args, **kwargs):
    """ Display calendar according to the required date. """
    date_today = datetime.date.today()
    today = {
        'day': date_today.strftime('%d'),
        'month': date_today.strftime('%m'),
        'year': date_today.strftime('%Y')
    }

    if kwargs:
        # Date that has been required in **kwargs:
        display_date = datetime.datetime(
            int(kwargs['year']), int(kwargs['month']), int(kwargs['day']))
    else:
        # Redirect to today:
        return redirect(reverse(
            'main:calendar',
            kwargs={
                'day': today['day'],
                'month': today['month'],
                'year': today['year'],
            }
        ))

    # Initial and last dates of the week containing the required date:
    initial_date = display_date - \
        datetime.timedelta(days=(display_date.weekday() + 1)
                           if display_date.weekday() != 6 else 0)
    initial_date_human = datetime.date(
        initial_date.year, initial_date.month, initial_date.day)

    # Construct the list of days with all their data:
    days = {}
    for i in range(7):
        coord_x = 0
        date = initial_date + datetime.timedelta(days=i)
        date_human = datetime.date(date.year, date.month, date.day)

        days[date_human] = {}
        days[date_human]['current'] = (date_human == datetime.date.today())
        days[date_human]['retreats'] = {}
        days[date_human]['sejours'] = {}
        days[date_human]['parloirs'] = {}

        # RETREATS:
        retreats = Retreat.objects.filter(
            date_from__lte=date)
        length_to_subtract_du = 2
        for index, retreat in enumerate(retreats):
            retreat_au = retreat.date_to()
            if retreat_au > initial_date_human:
                # Arrows:
                arrow_left = retreat.date_from < initial_date_human
                arrow_right = retreat_au > (
                    initial_date_human + datetime.timedelta(days=6))

                # Length and coord_x:
                # Max length allowed to the bar:
                max_length = 21 if (retreat.date_from < date_human) \
                    else (7 - i) * 3

                if retreat.date_from == date_human:
                    length = (((retreat_au - date_human).days) * 3)
                    coord_x = (i * 3) + 1 + length_to_subtract_du
                elif (retreat.date_from < date_human) \
                        and (retreat_au > (date_human + datetime.timedelta(days=7))) \
                        and (i == 0):
                    length = 21
                    coord_x = 1
                elif (retreat_au == date_human) \
                        and (retreat.date_from < initial_date_human):
                    length = (((date_human - initial_date_human).days) * 3) + 2
                    coord_x = 1
                else:
                    length = 0

                if length >= max_length:
                    length = max_length

                days[date_human]['retreats'][retreat] = {
                    'x': coord_x,
                    'length': length,
                    'arrow_left': arrow_left,
                    'arrow_right': arrow_right,
                }

        # SEJOURS:
        sejours = Sejour.objects.filter(
            sejour_du__lte=date).filter(sejour_au__gte=date)
        for index, sejour in enumerate(sejours):
            # Arrows:
            arrow_left = sejour.sejour_du < initial_date_human
            arrow_right = sejour.sejour_au > (
                initial_date_human + datetime.timedelta(days=6))

            # Priest:
            pretre = sejour.dit_messe

            # Rooms:
            chambres_nombre = sejour.chambre_set.count()
            chambres_string = sejour.chambres_string()

            # Length and coord_x:
            length_to_subtract_du = length_to_subtract_au = 0
            # Length to subtract at the beginning of the bar depending on repas_du:
            if not sejour.sejour_du < initial_date_human:
                if sejour.repas_du == 'Petit-déjeuner':
                    length_to_subtract_du = 0
                elif sejour.repas_du == 'Déjeuner':
                    length_to_subtract_du = 1
                elif sejour.repas_du == 'Dîner':
                    length_to_subtract_du = 2
            # Length to subtract at the end of the bar depending on repas_au:
            if not sejour.sejour_au > (initial_date_human + datetime.timedelta(days=6)):
                if sejour.repas_au == 'Petit-déjeuner':
                    length_to_subtract_au = 2
                elif sejour.repas_au == 'Déjeuner':
                    length_to_subtract_au = 1
                elif sejour.repas_au == 'Dîner':
                    length_to_subtract_au = 0

            # Max length allowed to the bar:
            max_length = 21 if (sejour.sejour_du < date_human) \
                else (7 - i) * 3

            if sejour.sejour_du == date_human:
                length = (((sejour.sejour_au - date_human).days + 1) * 3)
                coord_x = (i * 3) + 1 + length_to_subtract_du
            elif (sejour.sejour_du < date_human) \
                    and (sejour.sejour_au >= (date_human + datetime.timedelta(days=7))) \
                    and (i == 0):
                length = 21
                coord_x = 1
            elif (sejour.sejour_au == date_human) and (sejour.sejour_du < initial_date_human):
                length = (((date_human - initial_date_human).days + 1) * 3)
                coord_x = 1
            else:
                length = 0

            if length >= max_length:
                length = max_length
            else:
                length = length - length_to_subtract_du - length_to_subtract_au

            # Warnings about mails and oratory:
            warning_pere_suiveur = warning_sacristie = warning_oratoire = False
            if (sejour.personne.pere_suiveur is not None) and (not sejour.mail_pere_suiveur):
                warning_pere_suiveur = True
            if pretre and not sejour.mail_sacristie:
                warning_sacristie = True
            if pretre and not (sejour.oratoire or sejour.oratoire != ''):
                warning_oratoire = True

            days[date_human]['sejours'][sejour] = {
                'x': coord_x,
                'length': length,
                'arrow_left': arrow_left,
                'arrow_right': arrow_right,
                'pretre': pretre,
                'chambres_nombre': chambres_nombre,
                'chambres_string': chambres_string,
                'warning_pere_suiveur': warning_pere_suiveur,
                'warning_sacristie': warning_sacristie,
                'warning_oratoire': warning_oratoire,
            }

        # PARLOIRS:
        parloirs = Parloir.objects.filter(date=date).order_by('-date')
        for index, parloir in enumerate(parloirs):
            days[date_human]['parloirs'][parloir] = {
                'x': (i * 3) + 1,
                'length': 3,
            }

    return render(request, 'main/calendar.html', {
        'today': today,
        'days': days,
        'lines': range(21),
        'bold_lines': [2, 5, 8, 11, 14, 17, 20],
    })

hotellerie/templates/main.html
{% load static %}

<!DOCTYPE html>

<html>
    <head>
        <meta charset="UTF-8">
        <title>Hôtellerie</title>
        <link rel="icon" href={% static 'images/saint_joseph.png' %}>
        <link rel="stylesheet" href={% static 'js/jquery-ui-1.12.1/jquery-ui.min.css' %}>
        <link rel="stylesheet" href={% static 'css/fontawesome-free-5.7.1-web/css/all.min.css' %}>
        <link rel="stylesheet" href={% static 'css/bootstrap-4.0.0-dist/css/bootstrap.min.css' %}>
        <link rel="stylesheet" href={% static "css/tempusdominus-bootstrap-4.min.css" %}>
        <link rel="stylesheet/less" href={% static 'css/hotellerie.less' %}>
        {% block css %}{% endblock css %}
        
        <style>@font-face{font-family: "LucidaHW"; src: url("{% static 'fonts/TR Lucida Handwriting Italic.ttf' %}")}</style>
    </head>

    <body>
         <!-- The following block will not be displayed in listing cuisine. -->
         {% block nav_and_breadcrumbs %}
            <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
                <div id="logo" class="col-3 mr-auto">
                    <a href={% url 'main:calendar' %} class="d-flex align-items-center">
                        <p class="my-0">Hôtellerie</p>
                    </a>
                </div>

                {% if user.is_authenticated %}
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#main_menu" aria-controls="main_menu" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>

                    <div class="collapse navbar-collapse" id="main_menu">
                        <ul class="navbar-nav ml-auto">
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" id="user-menu" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    <span class="fas fa-align-justify"></span>
                                </a>
                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="user_menu">
                                    <a class="dropdown-item" href={% url 'main:calendar' %}>Calendrier</a>

                                    <div class="dropdown-divider"></div>

                                    <a class="dropdown-item" href={% url 'personnes:list' 'A' %}>Personnes</a>
                                    <a class="dropdown-item" href={% url 'sejours:list' %}>Séjours</a>
                                    <a class="dropdown-item" href={% url 'parloirs:list' %}>Parloirs</a>
                                    <a class="dropdown-item" href={% url 'retreats:list' %}>Retraites</a>

                                    <div class="dropdown-divider"></div>

                                    <a class="dropdown-item" href={% url 'listings:cuisine' %}>Listing cuisine</a>
                                    <a class="dropdown-item" href={% url 'listings:hotellerie' %}>Listing hôtellerie</a>

                                    <div class="dropdown-divider"></div>

                                    <a class="dropdown-item" href={% url 'accounts:logout' %}>Quitter</a>
                                </div>
                            </li>
                        </ul>
                    </div>
                {% endif %}
            </nav>

            <div id="breadcrumbs">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href={% url 'main:calendar' %}><span class="fas fa-home"></span></a></li>
                    {% block breadcrumbs %}
                    {% endblock breadcrumbs %}
                </ol>
            </div>
        {% endblock nav_and_breadcrumbs %}

        <div id="content" class="d-flex flex-column align-items-center mx-5 my-3">
            {% block content %}
            {% endblock content %}
        </div>
    </body>

    <script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
    <script src="{% static 'js/jquery-ui-1.12.1/jquery-ui.min.js' %}"></script>
    <script src="{% static 'css/bootstrap-4.0.0-dist/js/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'js/less.min.js' %}"></script>
    <script src="{% static "js/moment.min.js" %}"></script>
    <script src="{% static "js/moment-locale-fr.js" %}"></script>
    <script src="{% static "js/tempusdominus-bootstrap-4.min.js" %}"></script>
    <script src="{% static 'js/hotellerie.js' %}"></script>
    {% block javascript %}{% endblock javascript %}
</html>

hotellerie/templates/pagination.html
{% if is_paginated %}
    <nav aria-label="Topics pagination" class="mb-4">
        <ul class="pagination">
            {% if page_obj.has_previous %}
                <li class="page-item">
                    <a class="page-link" href="page={{ page_obj.previous_page_number }}">Previous</a>
                </li>
            {% else %}
                <li class="page-item disabled">
                    <span class="page-link">Previous</span>
                </li>
            {% endif %}

            {% for page_num in paginator.page_range %}
                {% if page_obj.number == page_num %}
                    <li class="page-item active">
                        <span class="page-link">
                            {{ page_num }}
                            <span class="sr-only">(current)</span>
                        </span>
                    </li>
                {% else %}
                    <li class="page-item">
                        <a class="page-link" href="page={{ page_num }}">{{ page_num }}</a>
                    </li>
                {% endif %}
            {% endfor %}

            {% if page_obj.has_next %}
                <li class="page-item">
                    <a class="page-link" href="page={{ page_obj.next_page_number }}">Next</a>
                </li>
            {% else %}
                <li class="page-item disabled">
                    <span class="page-link">Next</span>
                </li>
            {% endif %}
        </ul>
    </nav>
{% endif %}